// generated by @ng-toolkit/serverless
'use strict';
const server = require('./dist/server');
const functions = require('firebase-functions');
const admin = require("firebase-admin");
admin.initializeApp(functions.config().firebase);

const http = functions.https.onRequest((request, response) => {
  if (!request.path) {
    request.url = "/" + request.url;
  }
  return server.app(request, response);
});

const sendNotification = functions.firestore
  .document('/user/{value}').onCreate((snap, context) => {
    // ... Your code here
    // const data = snap.data();

    // let body = data.name ? ('Có khách hàng ' + data.name) : 'Có khách hàng mới';

    const payload = {
      notification: {
        title: 'New Message',
        body: 'body',
        icon: "https://financial-manage.firebaseapp.com/assets/images/home.jpg",
        click_action: "https://financial-manage.firebaseapp.com/admin/"
      }
    };
    var fcmTokens = admin.firestore().collection('fcmTokens');
    return fcmTokens.get()
      .then(snapshot => {
        snapshot.forEach(doc => {
          admin.messaging().sendToDevice(doc.data().token, payload).then(response => {
            // console.log("Send success")
          }).catch(function (error) {
            console.log("Error sending message:", error);
          });
        });
        return true;
      })
      .catch(err => {
        console.log('Error getting documents', err);
      });
  });

module.exports = {
  http,
  sendNotification
}
